-- Seed a substantial, reusable Coysh Digital client update template.

INSERT INTO email_templates (name, description, subject, preheader, content_json, status)
SELECT
    'Coysh Digital Client Update',
    'A polished, multi-section newsletter for sharing useful website and digital updates with clients.',
    'A useful digital update from Coysh Digital',
    'Practical ideas and updates to help your organisation get more from its website.',
    '{"theme":{"background":"#fdfafa","body":"#ffffff","text":"#264653","accent":"#a1c63e","font":"Arial, sans-serif","width":600},"blocks":[{"type":"heading","text":"A better digital presence starts here","level":1,"align":"left"},{"type":"text","html":"<p>Hi {{name}},</p><p>We are sharing a few practical ideas and updates to help {{company}} get more value from its website and digital channels.</p>","align":"left"},{"type":"divider"},{"type":"heading","text":"What is worth checking this month","level":2,"align":"left"},{"type":"columns","columns":[{"blocks":[{"type":"heading","text":"Performance","level":3,"align":"left"},{"type":"text","html":"<p>Fast, reliable pages create a better experience for visitors and make it easier for people to take the next step.</p>","align":"left"}]},{"blocks":[{"type":"heading","text":"Content","level":3,"align":"left"},{"type":"text","html":"<p>Clear, useful content helps the right people understand what you do and why they should choose you.</p>","align":"left"}]}]},{"type":"spacer","height":12},{"type":"heading","text":"A small action you can take","level":2,"align":"left"},{"type":"text","html":"<p>Choose one important page on your site and ask whether its message is still clear, current, and easy to act on. Small improvements compound over time.</p><ul><li>Check the page works well on a phone.</li><li>Make the next action obvious.</li><li>Refresh anything that is out of date.</li></ul>","align":"left"},{"type":"button","text":"Talk to Coysh Digital","url":"https://coysh.digital/contact","align":"left"},{"type":"divider"},{"type":"heading","text":"Need a second pair of eyes?","level":2,"align":"center"},{"type":"text","html":"<p>Reply to this email and we will be happy to discuss what would make the biggest difference for your organisation.</p>","align":"center"}]}',
    'active'
WHERE NOT EXISTS (SELECT 1 FROM email_templates WHERE name = 'Coysh Digital Client Update');
