<?php
$builderContent = $builderRecord['content_json'] ?? json_encode(CoyshCRM\Services\EmailRenderer::blankContent());
$assetOptions = array_map(fn($a)=>['id'=>(int)$a['id'],'name'=>$a['original_name'],'url'=>appUrl().'/email/assets/'.$a['public_token'].'/'.rawurlencode($a['original_name'])],$assets??[]);
?>
<div class="grid lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.8fr)] gap-5" id="email-builder">
<div class="space-y-4"><div class="bg-white border rounded-lg p-4"><div class="flex flex-wrap gap-2 items-end"><label class="text-xs">Accent<input type="color" id="theme-accent" class="block mt-1 h-9 w-14 border rounded"></label><label class="text-xs">Page<input type="color" id="theme-background" class="block mt-1 h-9 w-14 border rounded"></label><label class="text-xs">Body<input type="color" id="theme-body" class="block mt-1 h-9 w-14 border rounded"></label><label class="text-xs">Text<input type="color" id="theme-text" class="block mt-1 h-9 w-14 border rounded"></label><label class="text-xs">Font<select id="theme-font" class="block mt-1 border rounded px-2 py-2 text-sm"><option>Arial, sans-serif</option><option>Georgia, serif</option><option>Verdana, sans-serif</option><option>Tahoma, sans-serif</option></select></label><label class="text-xs">Width<input id="theme-width" type="number" min="480" max="680" class="block mt-1 border rounded px-2 py-2 text-sm w-24"></label></div></div>
<div class="bg-white border rounded-lg p-4"><div class="flex flex-wrap gap-2"><span class="text-sm font-medium mr-2 py-1">Add block</span><?php foreach(['heading'=>'Heading','text'=>'Text','image'=>'Image','button'=>'Button','divider'=>'Divider','spacer'=>'Spacer','columns'=>'2 columns'] as $type=>$label): ?><button type="button" data-add="<?= $type ?>" class="px-2 py-1 border rounded text-xs hover:bg-slate-50"><?= $label ?></button><?php endforeach ?></div></div><div id="builder-blocks" class="space-y-3"></div></div>
<div class="lg:sticky lg:top-4 self-start"><div class="flex justify-between items-center mb-2"><h2 class="font-medium text-sm">Live preview</h2><div class="flex gap-1"><button type="button" data-preview="desktop" class="px-2 py-1 border rounded text-xs">Desktop</button><button type="button" data-preview="mobile" class="px-2 py-1 border rounded text-xs">Mobile</button></div></div><div class="bg-slate-200 border rounded-lg p-4 overflow-auto"><div id="builder-preview" class="mx-auto bg-white shadow-sm transition-all"></div></div><p class="text-xs text-slate-400 mt-2">The sent email is rendered server-side with email-compatible tables and a required unsubscribe footer.</p></div>
</div><input type="hidden" name="content_json" id="content-json" value="<?= e($builderContent) ?>">
<script>
(function(){
const assets=<?= json_encode($assetOptions,JSON_UNESCAPED_SLASHES) ?>;let data;try{data=JSON.parse(document.getElementById('content-json').value)}catch(e){}if(!data||!Array.isArray(data.blocks))data={theme:{},blocks:[]};
data.theme=Object.assign({background:'#f1f5f9',body:'#ffffff',text:'#334155',accent:'#4f46e5',font:'Arial, sans-serif',width:600},data.theme||{});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function safeHtml(value){const template=document.createElement('template');template.innerHTML=String(value??'');const allowed=new Set(['DIV','P','BR','STRONG','B','EM','I','U','UL','OL','LI','A']);[...template.content.querySelectorAll('*')].forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(document.createTextNode(el.textContent||''));return}const href=el.tagName==='A'?el.getAttribute('href')||'':'';[...el.attributes].forEach(a=>el.removeAttribute(a.name));if(el.tagName==='A'&&/^(https?:|mailto:)/i.test(href))el.setAttribute('href',href)});return template.innerHTML}
function defaults(type){return {heading:{type,text:'New heading',level:2,align:'left'},text:{type,html:'<p>Write your message here.</p>',align:'left'},image:{type,asset_id:assets[0]?.id||0,alt:'',url:'',align:'center'},button:{type,text:'Learn more',url:'https://',align:'left'},divider:{type},spacer:{type,height:24},columns:{type,columns:[{blocks:[{type:'text',html:'<p>Left column</p>'}]},{blocks:[{type:'text',html:'<p>Right column</p>'}]}]}}[type]}
function input(label,value,key,i,type='text'){return `<label class="text-xs text-slate-500">${label}<input type="${type}" data-key="${key}" data-i="${i}" value="${esc(value)}" class="mt-1 w-full border rounded px-2 py-1.5 text-sm"></label>`}
function blockEditor(b,i){let body='';if(b.type==='heading')body=`<div class="grid grid-cols-[1fr_90px_100px] gap-2">${input('Text',b.text,'text',i)}${input('Level',b.level,'level',i,'number')}${select('Align',b.align,'align',i,['left','center','right'])}</div>`;
else if(b.type==='text')body=`<div><div class="flex flex-wrap gap-1 mb-1"><span class="text-xs text-slate-500 mr-2">Formatted text</span><button type="button" data-format="bold" class="px-2 border rounded text-xs font-bold">B</button><button type="button" data-format="italic" class="px-2 border rounded text-xs italic">I</button><button type="button" data-format="underline" class="px-2 border rounded text-xs underline">U</button><button type="button" data-format="insertUnorderedList" class="px-2 border rounded text-xs">List</button><button type="button" data-format="createLink" class="px-2 border rounded text-xs">Link</button><button type="button" data-insert="{{name}}" class="px-2 border rounded text-xs">+ name</button><button type="button" data-insert="{{company}}" class="px-2 border rounded text-xs">+ company</button></div><div contenteditable="true" data-rich data-i="${i}" class="min-h-24 w-full border rounded px-3 py-2 text-sm prose max-w-none">${safeHtml(b.html)}</div></div>${select('Align',b.align,'align',i,['left','center','right'])}`;
else if(b.type==='image')body=`<div class="grid grid-cols-2 gap-2">${assetSelect(b.asset_id,i)}${input('Alt text',b.alt,'alt',i)}${input('Optional link',b.url,'url',i)}${select('Align',b.align,'align',i,['left','center','right'])}</div>`;
else if(b.type==='button')body=`<div class="grid grid-cols-2 gap-2">${input('Label',b.text,'text',i)}${input('URL',b.url,'url',i)}${select('Align',b.align,'align',i,['left','center','right'])}</div>`;
else if(b.type==='spacer')body=input('Height (px)',b.height,'height',i,'number');
else if(b.type==='columns')body=`<div class="grid grid-cols-2 gap-2">${[0,1].map(ci=>`<div class="text-xs text-slate-500">Column ${ci+1}<div contenteditable="true" data-column-rich="${ci}" data-i="${i}" class="mt-1 min-h-24 w-full border rounded p-2 text-sm text-slate-700">${safeHtml(b.columns?.[ci]?.blocks?.[0]?.html||'')}</div></div>`).join('')}</div>`;
return `<div class="bg-white border rounded-lg p-4" data-block="${i}"><div class="flex justify-between mb-3"><span class="text-xs font-semibold uppercase text-slate-400">${esc(b.type)}</span><div class="flex gap-2"><button type="button" data-move="up" data-i="${i}" class="text-xs">↑</button><button type="button" data-move="down" data-i="${i}" class="text-xs">↓</button><button type="button" data-copy data-i="${i}" class="text-xs text-accent-600">Copy</button><button type="button" data-remove data-i="${i}" class="text-xs text-red-600">Remove</button></div></div>${body}</div>`}
function select(label,value,key,i,values){return `<label class="text-xs text-slate-500">${label}<select data-key="${key}" data-i="${i}" class="mt-1 w-full border rounded px-2 py-1.5 text-sm">${values.map(v=>`<option ${String(value)===String(v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function assetSelect(value,i){return `<label class="text-xs text-slate-500">Image<select data-key="asset_id" data-i="${i}" class="mt-1 w-full border rounded px-2 py-1.5 text-sm"><option value="0">Choose uploaded image</option>${assets.map(a=>`<option value="${a.id}" ${Number(value)===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label>`}
function draw(){document.getElementById('builder-blocks').innerHTML=data.blocks.map(blockEditor).join('');document.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>{let v=el.type==='number'?Number(el.value):el.value;data.blocks[Number(el.dataset.i)][el.dataset.key]=v;sync()});document.querySelectorAll('[data-rich]').forEach(el=>el.oninput=()=>{data.blocks[+el.dataset.i].html=el.innerHTML;sync()});document.querySelectorAll('[data-column-rich]').forEach(el=>el.oninput=()=>{data.blocks[+el.dataset.i].columns[+el.dataset.columnRich].blocks=[{type:'text',html:el.innerHTML}];sync()});document.querySelectorAll('[data-format]').forEach(el=>el.onmousedown=e=>{e.preventDefault();let value=null;if(el.dataset.format==='createLink'){value=prompt('Link URL (https:// or mailto:)');if(!value||!/^(https?:|mailto:)/i.test(value))return}document.execCommand(el.dataset.format,false,value)});document.querySelectorAll('[data-insert]').forEach(el=>el.onmousedown=e=>{e.preventDefault();document.execCommand('insertText',false,el.dataset.insert)});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{data.blocks.splice(+el.dataset.i,1);draw()});document.querySelectorAll('[data-copy]').forEach(el=>el.onclick=()=>{data.blocks.splice(+el.dataset.i+1,0,JSON.parse(JSON.stringify(data.blocks[+el.dataset.i])));draw()});document.querySelectorAll('[data-move]').forEach(el=>el.onclick=()=>{const i=+el.dataset.i,j=el.dataset.move==='up'?i-1:i+1;if(j<0||j>=data.blocks.length)return;[data.blocks[i],data.blocks[j]]=[data.blocks[j],data.blocks[i]];draw()});sync()}
function previewBlock(b){if(b.type==='heading')return `<h${b.level||2} style="text-align:${b.align||'left'};margin:0 0 12px;font-size:${b.level==1?30:b.level==3?19:24}px">${esc(b.text)}</h${b.level||2}>`;if(b.type==='text')return `<div style="text-align:${b.align||'left'};line-height:1.6">${safeHtml(b.html)}</div>`;if(b.type==='button')return b.url?`<div style="text-align:${b.align||'left'}"><span style="display:inline-block;padding:11px 18px;background:${data.theme.accent};color:white;border-radius:6px;font-weight:bold">${esc(b.text)}</span></div>`:'';if(b.type==='image'){const a=assets.find(a=>a.id===Number(b.asset_id));return a?`<img src="${esc(a.url)}" alt="${esc(b.alt)}" style="display:block;max-width:100%;height:auto;margin:${b.align==='center'?'auto':b.align==='right'?'0 0 0 auto':'0'}">`:'<div style="padding:28px;background:#f8fafc;text-align:center;color:#94a3b8">Choose an uploaded image</div>'}if(b.type==='divider')return '<hr style="border:0;border-top:1px solid #e2e8f0">';if(b.type==='spacer')return `<div style="height:${Math.max(8,Math.min(64,b.height||24))}px"></div>`;if(b.type==='columns')return `<div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">${(b.columns||[]).map(c=>`<div>${(c.blocks||[]).map(previewBlock).join('')}</div>`).join('')}</div>`;return ''}
function sync(){document.getElementById('content-json').value=JSON.stringify(data);const p=document.getElementById('builder-preview');p.style.background=data.theme.body;p.style.color=data.theme.text;p.style.fontFamily=data.theme.font;p.style.width=Math.min(data.theme.width||600,600)+'px';p.style.maxWidth='100%';p.style.padding='28px';p.innerHTML=data.blocks.map(b=>`<div style="margin-bottom:18px">${previewBlock(b)}</div>`).join('')+'<div style="border-top:1px solid #e2e8f0;padding-top:20px;text-align:center;font-size:12px;color:#64748b">Sender identity · Unsubscribe</div>';p.parentElement.style.background=data.theme.background}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{data.blocks.push(defaults(b.dataset.add));draw()});for(const key of ['accent','background','body','text','font','width']){const el=document.getElementById('theme-'+key);el.value=data.theme[key];el.oninput=()=>{data.theme[key]=key==='width'?Number(el.value):el.value;sync()}}document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{document.getElementById('builder-preview').style.width=b.dataset.preview==='mobile'?'320px':Math.min(data.theme.width||600,600)+'px'});draw();
})();
</script>
