<?php $edit=!empty($contact['id']); ?>
<div class="space-y-5 max-w-4xl"><?php include __DIR__.'/_nav.php'; ?><h1 class="text-xl font-semibold text-slate-800"><?= $edit?'Edit contact':'Add contact' ?></h1>
<form method="POST" action="<?= $edit?'/email/contacts/'.$contact['id']:'/email/contacts' ?>" class="bg-white border rounded-lg p-6 space-y-4"><?= csrfField() ?><input type="hidden" name="original_basis" value="<?= e($contact['eligibility_basis']??'unknown') ?>">
<div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Name<input name="name" value="<?= e($contact['name']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Email *<input type="email" required name="email" value="<?= e($contact['email']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Company<input name="company_name" value="<?= e($contact['company_name']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Contact status<select name="status" class="mt-1 w-full border rounded px-3 py-2"><option value="active">Active</option><option value="archived" <?= ($contact['status']??'')==='archived'?'selected':'' ?>>Archived</option></select></label></div>
<div class="border-t pt-4"><h2 class="font-medium text-sm">Marketing eligibility</h2><p class="text-xs text-slate-500 mb-3">Unknown contacts cannot be included in a send.</p><div class="grid sm:grid-cols-2 gap-4"><label class="text-sm">Basis<select name="eligibility_basis" class="mt-1 w-full border rounded px-3 py-2"><?php foreach(['unknown'=>'Needs review','consent'=>'Consent','soft_opt_in'=>'Soft opt-in','corporate_b2b'=>'Corporate B2B / legitimate interests'] as $v=>$l): ?><option value="<?= $v ?>" <?= ($contact['eligibility_basis']??'unknown')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach ?></select></label><label class="text-sm">Recorded at<input type="datetime-local" name="eligibility_at" value="<?= !empty($contact['eligibility_at'])?e(date('Y-m-d\TH:i',strtotime($contact['eligibility_at']))):'' ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Source<input name="eligibility_source" value="<?= e($contact['eligibility_source']??'') ?>" placeholder="Contract, signup form, client review…" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Evidence / notes<textarea name="eligibility_notes" rows="2" class="mt-1 w-full border rounded px-3 py-2"><?= e($contact['eligibility_notes']??'') ?></textarea></label></div></div>
<div><label class="block text-sm font-medium mb-1">Linked CRM clients</label><select name="client_ids[]" multiple size="7" class="w-full border rounded px-3 py-2 text-sm"><?php foreach($clients as $c): ?><option value="<?= $c['id'] ?>" <?= in_array($c['id'],$linked)?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach ?></select><p class="text-xs text-slate-400 mt-1">Hold Ctrl/Cmd to select multiple clients.</p></div>
<button class="px-4 py-2 bg-accent-600 text-white rounded text-sm">Save contact</button></form>
<?php if($edit): ?><div class="bg-white border rounded-lg p-4"><h2 class="font-medium text-sm mb-3">Suppression controls</h2><div class="flex flex-wrap gap-2"><form method="POST" action="/email/contacts/<?= $contact['id'] ?>/suppress"><?= csrfField() ?><input type="hidden" name="reason" value="manual"><button class="px-3 py-2 border border-red-300 text-red-700 rounded text-sm">Suppress</button></form><form method="POST" action="/email/contacts/<?= $contact['id'] ?>/resubscribe" class="flex gap-2"><?= csrfField() ?><input name="notes" required placeholder="Evidence of renewed permission" class="border rounded px-3 py-2 text-sm"><button class="px-3 py-2 border rounded text-sm">Record resubscription</button></form></div></div>
<?php if($history): ?><div class="bg-white border rounded-lg p-4"><h2 class="font-medium text-sm mb-2">Eligibility history</h2><?php foreach($history as $h): ?><div class="py-2 border-t text-sm"><span class="font-medium"><?= e(str_replace('_',' ',$h['event_type'])) ?></span> · <?= e($h['basis']) ?> <span class="text-slate-400"><?= e($h['occurred_at']) ?></span><p class="text-xs text-slate-500"><?= e($h['source']) ?> <?= e($h['notes']) ?></p></div><?php endforeach ?></div><?php endif ?><?php endif ?>
</div>
