<div class="space-y-6">
<?php include __DIR__.'/_nav.php'; ?>
<div class="flex items-center justify-between"><div><h1 class="text-xl font-semibold text-slate-800">Email Marketing</h1><p class="text-sm text-slate-500 mt-1">Build audiences, design campaigns, and follow delivery.</p></div><a href="/email/campaigns/create" class="px-4 py-2 bg-accent-600 text-white rounded text-sm font-medium">New campaign</a></div>
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
<?php foreach (['contacts'=>'Contacts','eligible'=>'Eligible to send','segments'=>'Segments','campaigns'=>'Campaigns'] as $key=>$label): ?><div class="bg-white border border-slate-200 rounded-lg p-4"><p class="text-xs uppercase tracking-wide text-slate-400"><?= $label ?></p><p class="text-2xl font-semibold text-slate-800 mt-1"><?= (int)$stats[$key] ?></p></div><?php endforeach ?>
</div>
<div class="bg-white border border-slate-200 rounded-lg overflow-hidden"><div class="px-4 py-3 border-b border-slate-200 flex justify-between"><h2 class="font-semibold text-sm text-slate-700">Recent campaigns</h2><a href="/email/campaigns" class="text-sm text-accent-600">View all</a></div>
<table class="w-full text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="text-left px-4 py-2">Campaign</th><th class="text-left px-4 py-2">Segment</th><th class="text-left px-4 py-2">Status</th><th class="text-right px-4 py-2">Delivered</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach($campaigns as $c): ?><tr><td class="px-4 py-3"><a class="text-accent-600 font-medium" href="/email/campaigns/<?= $c['id'] ?>"><?= e($c['name']) ?></a></td><td class="px-4 py-3 text-slate-500"><?= e($c['segment_name']?:'—') ?></td><td class="px-4 py-3"><?= e(ucfirst($c['status'])) ?></td><td class="px-4 py-3 text-right"><?= (int)$c['delivered'] ?>/<?= (int)$c['total_recipients'] ?></td></tr><?php endforeach ?><?php if(!$campaigns): ?><tr><td colspan="4" class="px-4 py-8 text-center text-slate-400">No campaigns yet.</td></tr><?php endif ?></tbody></table></div>
</div>
