<?php $edit=!empty($segment['id']);$included=[];$excluded=[];foreach($members as $m){${$m['action'].'d'}[]=(int)$m['contact_id'];} ?>
<div class="space-y-5 max-w-5xl"><?php include __DIR__.'/_nav.php'; ?><div class="flex justify-between items-center"><h1 class="text-xl font-semibold"><?= $edit?'Edit segment':'New segment' ?></h1><?php if($edit): ?><a href="/email/segments/<?= (int)$segment['id'] ?>" class="text-sm text-accent-600">View members</a><?php endif ?></div><form method="POST" action="<?= $edit?'/email/segments/'.$segment['id']:'/email/segments' ?>" class="space-y-5"><?= csrfField() ?>
<div class="bg-white border rounded-lg p-5 grid sm:grid-cols-2 gap-4"><label class="text-sm">Name *<input required name="name" value="<?= e($segment['name']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Type<select id="segment-type" name="segment_type" class="mt-1 w-full border rounded px-3 py-2"><option value="manual">Manual list</option><option value="dynamic" <?= ($segment['segment_type']??'')==='dynamic'?'selected':'' ?>>Dynamic rules + overrides</option></select></label><label class="text-sm sm:col-span-2">Description<input name="description" value="<?= e($segment['description']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label></div>
<div id="rules-panel" class="bg-white border rounded-lg p-5"><div class="flex justify-between items-center"><div><h2 class="font-medium">Dynamic rules</h2><select name="match_type" class="mt-2 border rounded px-2 py-1 text-sm"><option value="all">Match all rules</option><option value="any" <?= ($segment['match_type']??'')==='any'?'selected':'' ?>>Match any rule</option></select></div><button type="button" id="add-rule" class="px-3 py-2 border rounded text-sm">Add rule</button></div><div id="rules" class="mt-4 space-y-2"></div><input type="hidden" id="rules-json" name="rules_json" value="<?= e($segment['rules_json']??'[]') ?>"></div>
<div id="exclusions" class="bg-white border rounded-lg p-5"><div class="flex flex-wrap justify-between gap-3 items-end"><div><h2 class="font-medium mb-1">Contacts matching these rules</h2><p class="text-xs text-slate-400">The live rule result is shown here. Tick a contact to keep them excluded from this dynamic segment.</p></div><input id="segment-contact-filter" type="search" placeholder="Filter contacts" class="border rounded px-3 py-2 text-sm"></div><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead class="text-left text-xs uppercase text-slate-400 border-b"><tr><th class="py-2 pr-3">Exclude</th><th class="py-2 pr-3">Contact</th><th class="py-2">Email</th></tr></thead><tbody class="divide-y"><?php if(!$dynamicCandidates): ?><tr><td colspan="3" class="py-4 text-slate-400">Save rules to see matching contacts.</td></tr><?php else: foreach($dynamicCandidates as $c): ?><tr data-contact-row data-search="<?= e(strtolower(($c['name']??'').' '.$c['email'].' '.($c['company_name']??''))) ?>"><td class="py-2 pr-3"><input type="checkbox" name="exclude_ids[]" value="<?= (int)$c['id'] ?>" <?= in_array((int)$c['id'],$excluded,true)?'checked':'' ?>></td><td class="py-2 pr-3"><?= e($c['name']?:'Unnamed') ?></td><td class="py-2"><?= e($c['email']) ?></td></tr><?php endforeach; endif ?></tbody></table></div><p class="text-xs text-slate-400 mt-3"><?= count($dynamicCandidates) ?> live rule match<?= count($dynamicCandidates)===1?'':'es' ?>.</p></div>
<div class="bg-white border rounded-lg overflow-hidden">
    <div class="p-5 pb-3"><div class="flex flex-wrap justify-between gap-2 items-baseline"><h2 id="picker-title" class="font-medium">Contacts in this segment</h2><span class="text-sm"><strong id="picker-count">0</strong> selected</span></div><p id="picker-help" class="text-xs text-slate-400 mt-1"></p>
    <div class="flex flex-wrap gap-2 items-center mt-3"><input id="picker-search" type="search" placeholder="Search name, email, company or client…" class="border rounded px-3 py-2 text-sm flex-1 min-w-48"><select id="picker-status" class="border rounded px-3 py-2 text-sm"><option value="">All contacts</option><option value="1">Can be sent to</option><option value="0">Can't be sent to yet</option></select><label class="text-sm flex items-center gap-1"><input type="checkbox" id="picker-selected"> Selected only</label><button type="button" id="picker-all" class="px-3 py-2 border rounded text-sm">Select all shown</button><button type="button" id="picker-clear" class="px-3 py-2 border rounded text-sm">Clear shown</button></div></div>
    <div class="max-h-96 overflow-y-auto border-t"><table class="w-full text-sm"><thead class="text-left text-xs uppercase text-slate-400"><tr><th class="sticky top-0 bg-slate-50 px-4 py-2 w-8"></th><th class="sticky top-0 bg-slate-50 px-2 py-2">Contact</th><th class="sticky top-0 bg-slate-50 px-2 py-2">Company / clients</th><th class="sticky top-0 bg-slate-50 px-2 py-2">Eligibility</th></tr></thead><tbody class="divide-y">
    <?php if(!$contacts): ?><tr><td colspan="4" class="px-4 py-6 text-slate-400">No marketing contacts yet. <a href="/email/contacts/create" class="text-accent-600">Add a contact</a></td></tr><?php endif ?>
    <?php foreach($contacts as $c): $blocker=$c['status']!=='active'?'Archived':($c['suppression_reason']?'Suppressed: '.str_replace('_',' ',$c['suppression_reason']):($c['unsubscribed_at']?'Unsubscribed':null));$sendable=!$blocker&&$c['eligibility_basis']!=='unknown'; ?>
    <tr data-pick-row data-sendable="<?= $sendable?'1':'0' ?>" data-search="<?= e(strtolower(($c['name']??'').' '.$c['email'].' '.($c['company_name']??'').' '.($c['client_names']??''))) ?>" class="cursor-pointer hover:bg-slate-50">
        <td class="px-4 py-2"><input type="checkbox" name="include_ids[]" value="<?= (int)$c['id'] ?>" <?= in_array((int)$c['id'],$included,true)?'checked':'' ?>></td>
        <td class="px-2 py-2"><?= e($c['name']?:'Unnamed') ?><div class="text-xs text-slate-400"><?= e($c['email']) ?></div></td>
        <td class="px-2 py-2 text-slate-600"><?= e($c['company_name']?:$c['client_names']?:'—') ?><?php if($c['company_name']&&$c['client_names']&&$c['client_names']!==$c['company_name']): ?><div class="text-xs text-slate-400"><?= e($c['client_names']) ?></div><?php endif ?></td>
        <td class="px-2 py-2"><?php include __DIR__.'/_eligibility.php'; ?><?php if($blocker): ?> <span class="text-xs text-red-600"><?= e($blocker) ?></span><?php endif ?></td>
    </tr>
    <?php endforeach ?>
    <tr id="picker-none" style="display:none"><td colspan="4" class="px-4 py-6 text-slate-400">No contacts match that filter.</td></tr>
    </tbody></table></div>
</div>
<button class="px-4 py-2 bg-accent-600 text-white rounded text-sm">Save segment</button></form></div>
<script>
(function(){
const fields=<?= json_encode(\CoyshCRM\Services\SegmentEvaluator::FIELDS) ?>;
const operators=<?= json_encode(\CoyshCRM\Services\SegmentEvaluator::OPERATORS) ?>;
let rules=[];try{rules=JSON.parse(document.getElementById('rules-json').value)||[]}catch(e){}
function draw(){const root=document.getElementById('rules');root.innerHTML='';rules.forEach((r,i)=>{const row=document.createElement('div');row.className='grid grid-cols-[1fr_1fr_1fr_auto] gap-2';row.innerHTML=`<select class="border rounded px-2 py-2 text-sm field">${Object.entries(fields).map(([v,l])=>`<option value="${v}" ${r.field===v?'selected':''}>${l}</option>`).join('')}</select><select class="border rounded px-2 py-2 text-sm op">${Object.entries(operators).map(([v,l])=>`<option value="${v}" ${r.operator===v?'selected':''}>${l}</option>`).join('')}</select><input class="border rounded px-2 py-2 text-sm value" value="${String(r.value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><button type="button" class="text-red-600 px-2">Remove</button>`;row.querySelector('.field').onchange=e=>{r.field=e.target.value;sync()};row.querySelector('.op').onchange=e=>{r.operator=e.target.value;sync()};row.querySelector('.value').oninput=e=>{r.value=e.target.value;sync()};row.querySelector('button').onclick=()=>{rules.splice(i,1);draw()};root.appendChild(row)});sync()}
function sync(){document.getElementById('rules-json').value=JSON.stringify(rules)}document.getElementById('add-rule').onclick=()=>{rules.push({field:'client.status',operator:'equals',value:'active'});draw()};draw();
function filterContacts(input,selector){if(!input)return;input.oninput=()=>{const term=input.value.toLowerCase();document.querySelectorAll(selector).forEach(row=>{row.style.display=(row.dataset.search||'').includes(term)?'':'none'})}}filterContacts(document.getElementById('segment-contact-filter'),'[data-contact-row]');
// Contact picker: filtered-out rows are only hidden, so their ticks still submit.
const pickRows=[...document.querySelectorAll('[data-pick-row]')],pickSearch=document.getElementById('picker-search'),pickStatus=document.getElementById('picker-status'),pickSelected=document.getElementById('picker-selected');
const box=row=>row.querySelector('input[type=checkbox]');
function countPicked(){let n=0;pickRows.forEach(row=>{const on=box(row).checked;row.classList.toggle('bg-accent-50',on);if(on)n++});document.getElementById('picker-count').textContent=n}
function filterPicker(){const term=pickSearch.value.trim().toLowerCase();let shown=0;pickRows.forEach(row=>{const ok=(row.dataset.search||'').includes(term)&&(pickStatus.value===''||row.dataset.sendable===pickStatus.value)&&(!pickSelected.checked||box(row).checked);row.style.display=ok?'':'none';if(ok)shown++});document.getElementById('picker-none').style.display=pickRows.length&&!shown?'':'none'}
function setShown(on){pickRows.forEach(row=>{if(row.style.display!=='none')box(row).checked=on});countPicked();filterPicker()}
pickRows.forEach(row=>{row.onclick=e=>{if(e.target.tagName!=='INPUT')box(row).checked=!box(row).checked;countPicked()}});
pickSearch.oninput=filterPicker;pickStatus.onchange=filterPicker;pickSelected.onchange=filterPicker;document.getElementById('picker-all').onclick=()=>setShown(true);document.getElementById('picker-clear').onclick=()=>setShown(false);countPicked();
function toggle(){const dyn=document.getElementById('segment-type').value==='dynamic';document.getElementById('rules-panel').style.display=dyn?'block':'none';document.getElementById('exclusions').style.display=dyn?'block':'none';document.getElementById('picker-title').textContent=dyn?'Manual additions':'Contacts in this segment';document.getElementById('picker-help').textContent=dyn?'Optional: tick anyone who should be included even though they do not match the rules.':'Tick everyone who should receive campaigns sent to this segment. Contacts that cannot be sent to yet can still be added — they are skipped until their eligibility is recorded.'}document.getElementById('segment-type').onchange=toggle;toggle();
})();
</script>
