<?php $edit=!empty($segment['id']);$included=[];$excluded=[];foreach($members as $m){${$m['action'].'d'}[]=(int)$m['contact_id'];} ?>
<div class="space-y-5 max-w-5xl"><?php include __DIR__.'/_nav.php'; ?><h1 class="text-xl font-semibold"><?= $edit?'Edit segment':'New segment' ?></h1><form method="POST" action="<?= $edit?'/email/segments/'.$segment['id']:'/email/segments' ?>" class="space-y-5"><?= csrfField() ?>
<div class="bg-white border rounded-lg p-5 grid sm:grid-cols-2 gap-4"><label class="text-sm">Name *<input required name="name" value="<?= e($segment['name']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Type<select id="segment-type" name="segment_type" class="mt-1 w-full border rounded px-3 py-2"><option value="manual">Manual list</option><option value="dynamic" <?= ($segment['segment_type']??'')==='dynamic'?'selected':'' ?>>Dynamic rules + overrides</option></select></label><label class="text-sm sm:col-span-2">Description<input name="description" value="<?= e($segment['description']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label></div>
<div id="rules-panel" class="bg-white border rounded-lg p-5"><div class="flex justify-between items-center"><div><h2 class="font-medium">Dynamic rules</h2><select name="match_type" class="mt-2 border rounded px-2 py-1 text-sm"><option value="all">Match all rules</option><option value="any" <?= ($segment['match_type']??'')==='any'?'selected':'' ?>>Match any rule</option></select></div><button type="button" id="add-rule" class="px-3 py-2 border rounded text-sm">Add rule</button></div><div id="rules" class="mt-4 space-y-2"></div><input type="hidden" id="rules-json" name="rules_json" value="<?= e($segment['rules_json']??'[]') ?>"></div>
<div class="grid md:grid-cols-2 gap-4"><div class="bg-white border rounded-lg p-5"><h2 class="font-medium mb-1">Manual inclusions</h2><p class="text-xs text-slate-400 mb-3">The complete list for manual segments; forced additions for dynamic ones.</p><select multiple size="12" name="include_ids[]" class="w-full border rounded p-2 text-sm"><?php foreach($contacts as $c): ?><option value="<?= $c['id'] ?>" <?= in_array((int)$c['id'],$included,true)?'selected':'' ?>><?= e(($c['name']?$c['name'].' — ':'').$c['email']) ?></option><?php endforeach ?></select></div><div id="exclusions" class="bg-white border rounded-lg p-5"><h2 class="font-medium mb-1">Dynamic exclusions</h2><p class="text-xs text-slate-400 mb-3">People who match the rules but must remain removed.</p><select multiple size="12" name="exclude_ids[]" class="w-full border rounded p-2 text-sm"><?php foreach($contacts as $c): ?><option value="<?= $c['id'] ?>" <?= in_array((int)$c['id'],$excluded,true)?'selected':'' ?>><?= e(($c['name']?$c['name'].' — ':'').$c['email']) ?></option><?php endforeach ?></select></div></div><button class="px-4 py-2 bg-accent-600 text-white rounded text-sm">Save segment</button></form></div>
<script>
(function(){
const fields={
'contact.name':'Contact name','contact.email':'Contact email','contact.company_name':'Company','contact.status':'Contact status','contact.eligibility_basis':'Eligibility basis',
'client.name':'Client name','client.status':'Client status','client.client_type':'Client type','site.status':'Site status','site.website_stack':'Website stack','site.css_framework':'CSS framework','site.smtp_service':'SMTP service','site.server':'Server','domain.registrar':'Domain registrar','domain.cloudflare':'Uses Cloudflare','agreement.type':'Agreement type','agreement.status':'Agreement status','agreement.covers_hosting':'Agreement covers hosting','agreement.covers_support':'Agreement covers support','agreement.covers_maintenance':'Agreement covers maintenance'};
const operators={'equals':'equals','not_equals':'does not equal','contains':'contains','not_contains':'does not contain','is_empty':'is empty','is_not_empty':'is not empty','is_true':'is true','is_false':'is false'};
let rules=[];try{rules=JSON.parse(document.getElementById('rules-json').value)||[]}catch(e){}
function draw(){const root=document.getElementById('rules');root.innerHTML='';rules.forEach((r,i)=>{const row=document.createElement('div');row.className='grid grid-cols-[1fr_1fr_1fr_auto] gap-2';row.innerHTML=`<select class="border rounded px-2 py-2 text-sm field">${Object.entries(fields).map(([v,l])=>`<option value="${v}" ${r.field===v?'selected':''}>${l}</option>`).join('')}</select><select class="border rounded px-2 py-2 text-sm op">${Object.entries(operators).map(([v,l])=>`<option value="${v}" ${r.operator===v?'selected':''}>${l}</option>`).join('')}</select><input class="border rounded px-2 py-2 text-sm value" value="${String(r.value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><button type="button" class="text-red-600 px-2">Remove</button>`;row.querySelector('.field').onchange=e=>{r.field=e.target.value;sync()};row.querySelector('.op').onchange=e=>{r.operator=e.target.value;sync()};row.querySelector('.value').oninput=e=>{r.value=e.target.value;sync()};row.querySelector('button').onclick=()=>{rules.splice(i,1);draw()};root.appendChild(row)});sync()}
function sync(){document.getElementById('rules-json').value=JSON.stringify(rules)}document.getElementById('add-rule').onclick=()=>{rules.push({field:'client.status',operator:'equals',value:'active'});draw()};draw();
function toggle(){const dyn=document.getElementById('segment-type').value==='dynamic';document.getElementById('rules-panel').style.display=dyn?'block':'none';document.getElementById('exclusions').style.display=dyn?'block':'none'}document.getElementById('segment-type').onchange=toggle;toggle();
})();
</script>
