<?php $edit=!empty($segment['id']);$isDynamic=($segment['segment_type']??'')==='dynamic';$included=[];$excluded=[];foreach($members as $m){${$m['action'].'d'}[]=(int)$m['contact_id'];} ?>
<div class="space-y-5 max-w-5xl"><?php include __DIR__.'/_nav.php'; ?><h1 class="text-xl font-semibold"><?= $edit?'Edit segment':'New segment' ?></h1><form method="POST" action="<?= $edit?'/email/segments/'.$segment['id']:'/email/segments' ?>" class="space-y-5"><?= csrfField() ?>
<div class="bg-white border rounded-lg p-5 grid sm:grid-cols-2 gap-4"><label class="text-sm">Name *<input required name="name" value="<?= e($segment['name']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label><label class="text-sm">Type<select id="segment-type" name="segment_type" class="mt-1 w-full border rounded px-3 py-2"><option value="manual">Manual list</option><option value="dynamic" <?= ($segment['segment_type']??'')==='dynamic'?'selected':'' ?>>Dynamic rules + overrides</option></select></label><label class="text-sm sm:col-span-2">Description<input name="description" value="<?= e($segment['description']??'') ?>" class="mt-1 w-full border rounded px-3 py-2"></label></div>
<div id="rules-panel" class="bg-white border rounded-lg p-5"><div class="flex justify-between items-center"><div><h2 class="font-medium">Dynamic rules</h2><select name="match_type" class="mt-2 border rounded px-2 py-1 text-sm"><option value="all">Match all rules</option><option value="any" <?= ($segment['match_type']??'')==='any'?'selected':'' ?>>Match any rule</option></select></div><button type="button" id="add-rule" class="px-3 py-2 border rounded text-sm">Add rule</button></div><div id="rules" class="mt-4 space-y-2"></div><input type="hidden" id="rules-json" name="rules_json" value="<?= e($segment['rules_json']??'[]') ?>"></div>
<?php if($isDynamic): ?>
<div id="exclusions" class="bg-white border rounded-lg p-5"><div class="flex flex-wrap justify-between gap-3 items-end"><div><h2 class="font-medium mb-1">Contacts matching these rules</h2><p class="text-xs text-slate-400">The live rule result is shown here. Tick a contact to keep them excluded from this dynamic segment.</p></div><input id="segment-contact-filter" type="search" placeholder="Filter contacts" class="border rounded px-3 py-2 text-sm"></div><div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead class="text-left text-xs uppercase text-slate-400 border-b"><tr><th class="py-2 pr-3">Exclude</th><th class="py-2 pr-3">Contact</th><th class="py-2">Email</th></tr></thead><tbody class="divide-y"><?php if(!$dynamicCandidates): ?><tr><td colspan="3" class="py-4 text-slate-400">Save rules to see matching contacts.</td></tr><?php else: foreach($dynamicCandidates as $c): ?><tr data-contact-row data-search="<?= e(strtolower(($c['name']??'').' '.$c['email'])) ?>"><td class="py-2 pr-3"><input type="checkbox" name="exclude_ids[]" value="<?= (int)$c['id'] ?>" <?= in_array((int)$c['id'],$excluded,true)?'checked':'' ?>></td><td class="py-2 pr-3"><?= e($c['name']?:'Unnamed') ?></td><td class="py-2"><?= e($c['email']) ?></td></tr><?php endforeach; endif ?></tbody></table></div><p class="text-xs text-slate-400 mt-3"><?= count($dynamicCandidates) ?> live rule match<?= count($dynamicCandidates)===1?'':'es' ?>.</p></div>
<div class="bg-white border rounded-lg p-5"><h2 class="font-medium mb-1">Manual additions</h2><p class="text-xs text-slate-400 mb-3">Optional contacts to include even when they do not match the rules. This is a searchable list, not a select control.</p><input id="manual-contact-filter" type="search" placeholder="Filter contacts" class="border rounded px-3 py-2 text-sm mb-3 w-full sm:w-80"><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2"><?php foreach($contacts as $c): ?><label data-manual-contact data-search="<?= e(strtolower(($c['name']??'').' '.$c['email'])) ?>" class="flex items-start gap-2 border rounded p-2 text-sm"><input type="checkbox" name="include_ids[]" value="<?= (int)$c['id'] ?>" <?= in_array((int)$c['id'],$included,true)?'checked':'' ?>><span><span class="block"><?= e($c['name']?:'Unnamed') ?></span><span class="block text-xs text-slate-400"><?= e($c['email']) ?></span></span></label><?php endforeach ?></div></div>
<?php else: ?>
<div class="bg-white border rounded-lg p-5"><h2 class="font-medium mb-1">Contacts in this manual segment</h2><p class="text-xs text-slate-400 mb-3">Choose the contacts who should receive campaigns from this segment.</p><select multiple size="12" name="include_ids[]" class="w-full border rounded p-2 text-sm"><?php foreach($contacts as $c): ?><option value="<?= $c['id'] ?>" <?= in_array((int)$c['id'],$included,true)?'selected':'' ?>><?= e(($c['name']?$c['name'].' — ':'').$c['email']) ?></option><?php endforeach ?></select></div>
<?php endif ?><button class="px-4 py-2 bg-accent-600 text-white rounded text-sm">Save segment</button></form></div>
<script>
(function(){
const fields={
'contact.name':'Contact name','contact.email':'Contact email','contact.company_name':'Company','contact.status':'Contact status','contact.eligibility_basis':'Eligibility basis',
'client.name':'Client name','client.status':'Client status','client.client_type':'Client type','site.status':'Site status','site.website_stack':'Website stack','site.css_framework':'CSS framework','site.smtp_service':'SMTP service','site.server':'Server','domain.registrar':'Domain registrar','domain.cloudflare':'Uses Cloudflare','agreement.type':'Agreement type','agreement.status':'Agreement status','agreement.covers_hosting':'Agreement covers hosting','agreement.covers_support':'Agreement covers support','agreement.covers_maintenance':'Agreement covers maintenance'};
const operators={'equals':'equals','not_equals':'does not equal','contains':'contains','not_contains':'does not contain','is_empty':'is empty','is_not_empty':'is not empty','is_true':'is true','is_false':'is false'};
let rules=[];try{rules=JSON.parse(document.getElementById('rules-json').value)||[]}catch(e){}
function draw(){const root=document.getElementById('rules');root.innerHTML='';rules.forEach((r,i)=>{const row=document.createElement('div');row.className='grid grid-cols-[1fr_1fr_1fr_auto] gap-2';row.innerHTML=`<select class="border rounded px-2 py-2 text-sm field">${Object.entries(fields).map(([v,l])=>`<option value="${v}" ${r.field===v?'selected':''}>${l}</option>`).join('')}</select><select class="border rounded px-2 py-2 text-sm op">${Object.entries(operators).map(([v,l])=>`<option value="${v}" ${r.operator===v?'selected':''}>${l}</option>`).join('')}</select><input class="border rounded px-2 py-2 text-sm value" value="${String(r.value||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"><button type="button" class="text-red-600 px-2">Remove</button>`;row.querySelector('.field').onchange=e=>{r.field=e.target.value;sync()};row.querySelector('.op').onchange=e=>{r.operator=e.target.value;sync()};row.querySelector('.value').oninput=e=>{r.value=e.target.value;sync()};row.querySelector('button').onclick=()=>{rules.splice(i,1);draw()};root.appendChild(row)});sync()}
function sync(){document.getElementById('rules-json').value=JSON.stringify(rules)}document.getElementById('add-rule').onclick=()=>{rules.push({field:'client.status',operator:'equals',value:'active'});draw()};draw();
function filterContacts(input,selector){if(!input)return;input.oninput=()=>{const term=input.value.toLowerCase();document.querySelectorAll(selector).forEach(row=>{row.style.display=(row.dataset.search||'').includes(term)?'':'none'})}}filterContacts(document.getElementById('segment-contact-filter'),'[data-contact-row]');filterContacts(document.getElementById('manual-contact-filter'),'[data-manual-contact]');
function toggle(){const dyn=document.getElementById('segment-type').value==='dynamic';document.getElementById('rules-panel').style.display=dyn?'block':'none';const exclusions=document.getElementById('exclusions');if(exclusions)exclusions.style.display=dyn?'block':'none'}document.getElementById('segment-type').onchange=toggle;toggle();
})();
</script>
